import 'package:flutter/material.dart';

class CategoryIconGroup {
  final String name;
  final List<IconData> icons;

  const CategoryIconGroup(this.name, this.icons);
}

const List<CategoryIconGroup> categoryIconGroups = [
  CategoryIconGroup('Common', [
    Icons.shopping_bag,
    Icons.fastfood,
    Icons.directions_car,
    Icons.home,
    Icons.local_hospital,
    Icons.sports_soccer,
    Icons.movie,
    Icons.school,
    Icons.flight,
    Icons.pets,
    Icons.work,
    Icons.wifi,
    Icons.phone,
    Icons.monetization_on,
    Icons.account_balance,
  ]),
  CategoryIconGroup('Food & Drink', [
    Icons.restaurant,
    Icons.coffee,
    Icons.local_bar,
    Icons.bakery_dining,
    Icons.icecream,
    Icons.lunch_dining,
    Icons.local_pizza,
    Icons.liquor,
    Icons.egg_alt,
    Icons.kitchen,
  ]),
  CategoryIconGroup('Transport', [
    Icons.commute,
    Icons.directions_bus,
    Icons.directions_subway,
    Icons.directions_bike,
    Icons.local_taxi,
    Icons.electric_car,
    Icons.moped,
    Icons.pedal_bike,
    Icons.anchor,
    Icons.rocket_launch,
  ]),
  CategoryIconGroup('Shopping', [
    Icons.shopping_cart,
    Icons.store,
    Icons.checkroom,
    Icons.local_mall,
    Icons.card_giftcard,
    Icons.wallet,
    Icons.point_of_sale,
    Icons.redeem,
    Icons.inventory_2,
    Icons.qr_code_2,
  ]),
  CategoryIconGroup('Entertainment', [
    Icons.celebration,
    Icons.theater_comedy,
    Icons.music_note,
    Icons.videogame_asset,
    Icons.casino,
    Icons.camera_alt,
    Icons.stadium,
    Icons.local_activity,
    Icons.brush,
    Icons.piano,
  ]),
  CategoryIconGroup('Health & Personal', [
    Icons.fitness_center,
    Icons.spa,
    Icons.medication,
    Icons.psychology,
    Icons.self_improvement,
    Icons.blind,
    Icons.clean_hands,
    Icons.bed,
    Icons.soap,
    Icons.face,
  ]),
  CategoryIconGroup('Home & Utilities', [
    Icons.electric_bolt,
    Icons.water_drop,
    Icons.propane,
    Icons.ac_unit,
    Icons.construction,
    Icons.cleaning_services,
    Icons.plumbing,
    Icons.security,
    Icons.grass,
    Icons.deck,
  ]),
  CategoryIconGroup('Work & Finance', [
    Icons.laptop,
    Icons.print,
    Icons.terminal,
    Icons.trending_up,
    Icons.trending_down,
    Icons.savings,
    Icons.price_check,
    Icons.attach_money,
    Icons.euro,
    Icons.credit_card,
  ]),
  CategoryIconGroup('Travel', [
    Icons.hotel,
    Icons.map,
    Icons.explore,
    Icons.luggage,
    Icons.beach_access,
    Icons.landscape,
    Icons.navigation,
    Icons.backpack,
    Icons.train,
    Icons.castle,
  ]),
];
